In [1]:
import seaborn as sns

In [2]:
df = sns.load_dataset('brain_networks')

In [4]:
df.head()

,network,1,1.1,2,2.1,3,3.1,4,4.1,5,...,16.5,16.6,16.7,17,17.1,17.2,17.3,17.4,17.5,17.6
0,node,1,1,1,1,1,1,1,1,1,...,3,4,4,1,1,2,2,3,3,4
1,hemi,lh,rh,lh,rh,lh,rh,lh,rh,lh,...,rh,lh,rh,lh,rh,lh,rh,lh,rh,lh
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,56.05574417114258,92.03103637695312,3.391575574874878,38.65968322753906,26.203819274902344,-49.71556854248047,47.4610366821289,26.746612548828125,-35.898860931396484,...,0.6079040169715881,-70.27054595947266,77.36577606201172,-21.73455047607422,1.0282527208328247,7.7917842864990225,68.90372467041016,-10.520872116088867,120.49046325683594,-39.686431884765625
4,1,55.5472526550293,43.6900749206543,-65.49598693847656,-13.974522590637207,-28.27496337890625,-39.05012893676758,-1.2106596231460571,-19.012897491455078,19.568010330200195,...,57.49507141113281,-76.39321899414062,127.26136016845705,-13.035799026489258,46.3818244934082,-15.752449989318848,31.00033187866211,-39.607521057128906,24.76401138305664,-36.7710075378418

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 923 entries, 0 to 922
Data columns (total 63 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   network  922 non-null    object
 1   1        922 non-null    object
 2   1.1      922 non-null    object
 3   2        922 non-null    object
 4   2.1      922 non-null    object
 5   3        922 non-null    object
 6   3.1      922 non-null    object
 7   4        922 non-null    object
 8   4.1      922 non-null    object
 9   5        922 non-null    object
 10  5.1      922 non-null    object
 11  6        922 non-null    object
 12  6.1      922 non-null    object
 13  6.2      922 non-null    object
 14  6.3      922 non-null    object
 15  7        922 non-null    object
 16  7.1      922 non-null    object
 17  7.2      922 non-null    object
 18  7.3      922 non-null    object
 19  7.4      922 non-null    object
 20  7.5      922 non-null    object
 21  8        922 non-null    object
 22  8.1      922 non-null    object
 23  8.2      922 non-null    object
 24  8.3      922 non-null    object
 25  8.4      922 non-null    object
 26  8.5      922 non-null    object
 27  9        922 non-null    object
 28  9.1      922 non-null    object
 29  10       922 non-null    object
 30  10.1     922 non-null    object
 31  11       922 non-null    object
 32  11.1     922 non-null    object
 33  12       922 non-null    object
 34  12.1     922 non-null    object
 35  12.2     922 non-null    object
 36  12.3     922 non-null    object
 37  12.4     922 non-null    object
 38  13       922 non-null    object
 39  13.1     922 non-null    object
 40  13.2     922 non-null    object
 41  13.3     922 non-null    object
 42  13.4     922 non-null    object
 43  13.5     922 non-null    object
 44  14       922 non-null    object
 45  14.1     922 non-null    object
 46  15       922 non-null    object
 47  15.1     922 non-null    object
 48  16       922 non-null    object
 49  16.1     922 non-null    object
 50  16.2     922 non-null    object
 51  16.3     922 non-null    object
 52  16.4     922 non-null    object
 53  16.5     922 non-null    object
 54  16.6     922 non-null    object
 55  16.7     922 non-null    object
 56  17       922 non-null    object
 57  17.1     922 non-null    object
 58  17.2     922 non-null    object
 59  17.3     922 non-null    object
 60  17.4     922 non-null    object
 61  17.5     922 non-null    object
 62  17.6     922 non-null    object
dtypes: object(63)
memory usage: 454.4+ KB